import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import GraphComponent from "@/components/graph-component";
import jsonDataFirst from "./json1.json";
import jsonDataSecond from "./json2.json";
import jsonDataThird from "./json3.json";
import React, { useState } from "react";
import GraphViewer from "@/components/graph-component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <GraphViewer />
      </main>
    </>
  );
}
